# Generated by Django 3.2.7 on 2021-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('emailKey', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('hasVoted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voteKey', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('candidate', models.CharField(max_length=100)),
                ('vote', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('voteKey', 'category', 'candidate')},
            },
        ),
    ]
